<?php

  global $response;

  if ( !function_exists('wp_handle_upload') ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
  }

  /*
    Inputs required:
    - name
    - email
    - purchase
    - amount
    - iban
    - owner
    - committee
    - post
    - date
    - file
  */

	/**
	 * Send the email and return the success rate
	 * @return bool
	 */
  function send_decl() {

    $name = esc_html($_POST['name']);
    $email = esc_html($_POST['email']);
    $purchase = esc_html($_POST['purchase']);
    $amount = strval(esc_html($_POST['amount']));
    $iban = esc_html($_POST['iban']);
    $owner = esc_html($_POST['owner']);
    $committee = explode(';', esc_html($_POST['committee']), 2);
    $post = esc_html($_POST['post']);
    $date = esc_html($_POST['date']);

		$options = get_option('id_settings');
    $receiver_name = $options['id_declaration_name_addresses_field'];
    $receiver_email = $options['id_declaration_email_addresses_field'];
    $receiver = "$receiver_name <$receiver_email>, $committee[0] <$committee[1]>";

		$subject = "Declaration from $name";

    $body = "<p>Lieve $receiver_name and committee treasurer,</p>
    <p>How nice, $name bought <b>$purchase</b>!</p>
    <p>They spent: € <b>$amount</b><br>
    They would like you to transfer it to: <b>$iban</b>, t.n.v. <b>$owner</b><br>
    It was bought for: <b>$committee[0]</b> under post <b>$post</b><br>
    The $purchase was bought on: <b>$date</b></p>
    <p>For questions, you should email $email</p>
    <p>Liefs</p>";

		$sender = "$name <$email>";

    $uploadedfile = $_FILES['file'];

    $upload_overrides = array(
      'test_form' => false
    );

    $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

    if ( $movefile && !isset($movefile['error']) ) {
      $attachments = [$movefile['file']];
      if ( send_mail($receiver, $subject, $body, $sender, $attachments) ) {
        wp_delete_file($movefile['file']);
        return true;
      } else {
        return false;
      }
    } else {
      /* Error generated by _wp_handle_upload()
      * @see _wp_handle_upload() in wp-admin/includes/file.php */
      $response['file_error'] = $movefile['error'];
      return false;
    }

  }

  validate_form('send_decl');
